name: Deployer LLIO
on:
  push:
    branches:
      - main
      - JL_AutoDeploy_DEV
    paths:
      - "API/**"
      - "LLIO2025/**"

jobs:
  deploy-api:
    if: contains(github.event.head_commit.modified, 'API/')
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Go API
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.DEV_SSH_HOST}}
          key: ${{secrets.DEV_SSH_KEY}}
          username: ${{ secrets.SSH_USERNAME}}
          debug: true
          script: |
            echo "Starting API deployment..."
            cd /root/ProjetLLIO2025/GestionnaireHoraire
            echo "Current directory: $(pwd)"
            echo "Stopping API service..."
            sudo systemctl stop llio-api.service
            echo "Pulling latest changes..."
            git pull origin JL_AutoDeploy_DEV
            cd API
            echo "Running go mod tidy..."
            go mod tidy
            echo "Starting API service..."
            sudo systemctl start llio-api
            echo 'API deployment successful'

  deploy-frontend:
    if: contains(github.event.head_commit.modified, 'LLIO2025/')
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Svelte Frontend
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.DEV_SSH_HOST}}
          key: ${{secrets.DEV_SSH_KEY}}
          username: ${{ secrets.SSH_USERNAME}}
          debug: true
          script: |
            echo "Starting Frontend deployment..."
            cd /root/ProjetLLIO2025/GestionnaireHoraire
            echo "Current directory: $(pwd)"
            echo "Stopping frontend service..."
            sudo systemctl stop llio-frontend.service
            echo "Pulling latest changes..."
            git pull origin JL_AutoDeploy_DEV
            cd LLIO2025
            echo "Installing dependencies..."
            npm install
            echo "Building application..."
            npm run build
            echo "Starting frontend service..."
            sudo systemctl start llio-frontend
            echo 'Frontend deployment successful'
