name: Deployer LLIO
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Full Application
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.DEV_SSH_HOST}}
          key: ${{secrets.DEV_SSH_KEY}}
          username: ${{ secrets.SSH_USERNAME}}
          debug: true
          script: |
            set -e # Exit immediately if a command exits with a non-zero status.
            echo "Starting deployment process..."

            # Arrêt des services
            echo "Stopping services..."
            sudo systemctl stop llio-api.service || echo "API service not running"
            sudo systemctl stop llio-frontend.service || echo "Frontend service not running"

            # Suppression et récréation du répertoire GestionnaireHoraire
            echo "Refreshing project directory..."
            cd /root/ProjetLLIO2025
            rm -rf GestionnaireHoraire

            # Clone du projet (plus propre qu'un pull)
            echo "Cloning fresh repository..."
            git clone https://github.com/ecoleduweb/GestionnaireHoraire.git

            # Configuration API
            echo "Configuring API..."
            cd /root/ProjetLLIO2025/GestionnaireHoraire/API
            cat > .env << EOF
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            DB_HOST=${{ secrets.DB_HOST }}
            DB_PORT=${{ secrets.DB_PORT }}
            DB_NAME_RUN=${{ secrets.DB_NAME_RUN }}
            DB_NAME_TEST=${{ secrets.DB_NAME_TEST }}
            ENV=${{ secrets.ENV }}
            AZUREAD_CLIENT_ID=${{ secrets.AZUREAD_CLIENT_ID }}
            AZUREAD_CLIENT_SECRET=${{ secrets.AZUREAD_CLIENT_SECRET }}
            AZUREAD_CALLBACK_URL=${{ secrets.AZUREAD_CALLBACK_URL }}
            SESSION_MAX_AGE=${{ secrets.SESSION_MAX_AGE }}
            SESSION_SECRET=${{ secrets.SESSION_SECRET }}
            FRONTEND_URL=${{ secrets.FRONTEND_URL }}
            JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}
            EOF

            echo "Building API..."
            /usr/local/go/bin/go mod tidy
            /usr/local/go/bin/go build -o app

            # Configuration Frontend
            echo "Configuring Frontend..."
            cd /root/ProjetLLIO2025/GestionnaireHoraire/LLIO2025
            cat > .env << EOF
            VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }}
            BASE_PATH=/llio-frontend
            EOF

            echo "Building Frontend..."
            npm install
            npm run build

            # Démarrage des services
            echo "Starting services..."
            sudo systemctl start llio-api || echo "Failed to start API service"
            sudo systemctl start llio-frontend || echo "Failed to start Frontend service"

            # Vérification
            echo "Checking services status..."
            sudo systemctl status llio-api --no-pager
            sudo systemctl status llio-frontend --no-pager

            echo "Deployment completed successfully!"
